driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.8.1

platforms:
  - name: centos-7.1
  - name: ubuntu-16.04

suites:
  - name: default
    run_list:
      - recipe[taurus::default]

