name 'taurus'
maintainer 'Perf Suite'
maintainer_email 'perf-suite@outlook.com'
license 'Apache 2.0'
description 'Installs/Configures taurus performance tools'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version '3.0.0'
source_url 'https://github.com/perf-suite/taurus'
issues_url 'https://github.com/perf-suite/taurus/issues'

# conflicts 'yum', '>= 4.0.0'
# depends 'yum', '~> 3.0.0', '< 4.0.0'

supports 'centos'
supports 'ubuntu'

depends 'ark'
depends 'build-essential'
depends 'apt'
depends 'yum', '= 3.13.0', '= 3.8.2'
depends 'yum-epel', '~> 1.0.0'
depends 'java'
depends 'python'
depends 'erlang'
depends 'runit'
depends 'firewall'
